apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-draft
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  image: {{image}}
  port: 7070
  liveness:
    path: /modiapersonoversikt-draft/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-draft/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-draft/internal/metrics
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1024Mi
  ingresses:
    - https://app.adeo.no/modiapersonoversikt-draft
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 85
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: prod-fss
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  env:
    - name: DATABASE_JDBC_URL
      value: "jdbc:postgresql://A01DBVL009.adeo.no:5432/modiapersonoversikt-draft"
    - name: VAULT_MOUNTPATH
      value: "postgresql/prod-fss"
