apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-draft
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  image: "{{image}}"
  port: 7070
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1024Mi
  ingresses:
    - https://modiapersonoversikt-draft.intern.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 85
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: modiapersonoversikt-draft-db
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: prod-gcp
  env:
    - name: DATABASE_NAME
      value: "modiapersonoversikt-draft-db"
